version: '3'
services:
  postgres:
    restart: always
    build:
      context: ./database
      dockerfile: Docker-postgres
    environment:
      - POSTGRES_USER=ratch_user
      - POSTGRES_PASSWORD=ratch
      - POSTGRES_DB=ratch_db
    volumes:
      - /etc/hosts:/etc/hosts:rw
      - db_data:/var/lib/postgresql/data:delegated
    ports:
      - 5432:5432
    networks:
      - db_network

  ratch-app:
    restart: always
    env_file: .env
    build: .
    volumes:
      - ./app:/app
    ports:
      - 80:5000
    networks:
      - db_network
      - web_network

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - 85:85
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - ratch-app

  pgadmin:
    image: dpage/pgadmin4:4.20
    user: 5050:5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
    links:
      - postgres
    networks:
      - db_network
    ports:
      - 8080:80
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  db_data: {}
