version: '3'
services:

  postgres:
    restart: always
    build:
      context: postgres
      dockerfile: Docker-postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - /etc/hosts:/etc/hosts:rw
      - db_data:/var/lib/postgresql/data:delegated
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - db_network

  ratch-app:
    restart: always
    env_file: .env
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    networks:
      - db_network
      - web_network
    depends_on: 
      - postgres

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - ratch-app

#  pgadmin:
#    image: dpage/pgadmin4:latest
#    user: 5050:5050
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=user@domain.com
#      - PGADMIN_DEFAULT_PASSWORD=password
#    links:
#      - postgres
#    networks:
#      - db_network
#    ports:
#      - 8080:80

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  db_data: {}
